name: Pipeline

on:
  push:
    branches: [ "cicd_test" ]

env:
  REGISTRY: ghcr.io
  MENU_IMAGE_NAME: ${{ github.repository }}/menu
  WAITER_IMAGE_NAME: ${{ github.repository }}/waiter
  CHEF_IMAGE_NAME: ${{ github.repository }}/chef

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Menu service
      uses: docker/build-push-action@v5
      with:
        context: ./src/menu
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.MENU_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.MENU_IMAGE_NAME }}:latest
        
    - name: Build and push Waiter service
      uses: docker/build-push-action@v5
      with:
        context: ./src/waiter
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.WAITER_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.WAITER_IMAGE_NAME }}:latest
        
    - name: Build and push Chef service
      uses: docker/build-push-action@v5
      with:
        context: ./src/chef
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.CHEF_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.CHEF_IMAGE_NAME }}:latest
