menu:
  image:
    repository: acrad0mka.azurecr.io/menu  # For local: restaurant/menu
    tag: latest
    pullPolicy: Always
  config:
    port: "8080"

waiter:
  image:
    repository: acrad0mka.azurecr.io/waiter  # For local: restaurant/waiter
    tag: latest
    pullPolicy: Always
  config:
    port: "8081"

rabbitmq: 
  host: "host.minikube.internal"
  port: "5672"
  user: "guest"
  password: "guest"
  vhost: "/"

postgres:
  host: "host.minikube.internal"
  port: "5432"
  database: "restaurant"
  user: "restaurant"
  password: "devpassword"