menu:
  image:
    repository: restaurant/menu  # For local: restaurant/menu
    tag: latest
    pullPolicy: Never            # For local: Never
  config:
    port: "8080"

waiter:
  image:
    repository: restaurant/waiter  # For local: restaurant/waiter
    tag: latest
    pullPolicy: Never              # For local: Never
  config:
    port: "8081"

rabbitmq: 
  host: "rabbitmq"
  port: "5672"
  user: "guest"
  password: "guest"
  vhost: "/"

postgres:
  host: "postgres"
  port: "5432"
  database: "restaurant"
  user: "restaurant"
  password: "devpassword"

chef:
  image:
    repository: restaurant/chef  # For local: restaurant/chef
    tag: latest
    pullPolicy: Never            # For local: Never
  config:
    port: "8080"
