apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
data:
  MENU_PORT: {{ .Values.menu.config.port | quote }}
  WAITER_PORT: {{ .Values.waiter.config.port | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}

