apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      imagePullSecrets:
        - name: acr-secret
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "Waiting for postgres..."; sleep 2; done; echo "Postgres is up!"']
      containers:
      - name: menu
        image: "{{ .Values.menu.image.repository }}:{{ .Values.menu.image.tag }}"
        imagePullPolicy: {{ .Values.menu.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.menu.config.port }}
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: restaurant-config
              key: MENU_PORT
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
        envFrom:
        - configMapRef:
            name: restaurant-config
        - secretRef:
            name: restaurant-secret
