apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.user | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | b64enc | quote }}
