apiVersion: v1
kind: Service
metadata:
  name: waiter
spec:
  selector:
    app: waiter
  ports:
  - port: {{ .Values.waiter.config.port }}
    targetPort: {{ .Values.waiter.config.port }}
  type: NodePort