name: Pipeline

on:
  push:
    branches: [ "main" ]

env:
  MENU_IMAGE_NAME: menu
  WAITER_IMAGE_NAME: waiter
  CHEF_IMAGE_NAME: chef

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_URL }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
        
    - name: Build and push Menu service
      uses: docker/build-push-action@v5
      with:
        context: ./src/menu
        push: true
        tags: ${{ secrets.AZURE_ACR_URL }}/menu:${{ github.sha }},${{ secrets.AZURE_ACR_URL }}/menu:latest
        
    - name: Build and push Waiter service
      uses: docker/build-push-action@v5
      with:
        context: ./src/waiter
        push: true
        tags: ${{ secrets.AZURE_ACR_URL }}/waiter:${{ github.sha }},${{ secrets.AZURE_ACR_URL }}/waiter:latest
        
    - name: Build and push Chef service
      uses: docker/build-push-action@v5
      with:
        context: ./src/chef
        push: true
        tags: ${{ secrets.AZURE_ACR_URL }}/chef:${{ github.sha }},${{ secrets.AZURE_ACR_URL }}/chef:latest
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Get AKS Credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Create ACR Secret
      run: |
        kubectl create secret docker-registry acr-secret \
          --docker-server=${{ secrets.AZURE_ACR_URL }} \
          --docker-username=${{ secrets.AZURE_ACR_USERNAME }} \
          --docker-password=${{ secrets.AZURE_ACR_PASSWORD }} \
          --dry-run=client -o yaml | kubectl apply -f -
      
    - name: Deploy to AKS
      run: |
        if helm list | grep -q "restaurant"; then
          # Upgrade existing deployment
          helm upgrade restaurant ./src/restaurant \
            --set menu.image.tag=${{ github.sha }} \
            --set waiter.image.tag=${{ github.sha }} \
            --set chef.image.tag=${{ github.sha }}
        else
          # First deployment
          helm install restaurant ./src/restaurant \
            --set menu.image.tag=${{ github.sha }} \
            --set waiter.image.tag=${{ github.sha }} \
            --set chef.image.tag=${{ github.sha }}
        fi














