name: Pipeline

on:
  push:
    branches: [ "cicd_test" ]

env:
  FORCE_BUILD: false
  VERSION: ${{ format('{0}{1}', 'v', github.run_number) }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      menu: ${{ steps.filter.outputs.menu }}
      waiter: ${{ steps.filter.outputs.waiter }}
      chef: ${{ steps.filter.outputs.chef }}
      force_build: ${{ steps.set_force.outputs.force }}
    steps:
    - uses: actions/checkout@v4
    - name: Set force build output
      id: set_force
      run: |
        echo "force=${{ env.FORCE_BUILD }}" >> $GITHUB_OUTPUT
    - name: Debug Environment
      run: |
        echo "FORCE_BUILD from env: ${{ env.FORCE_BUILD }}"
        echo "FORCE_BUILD directly: $FORCE_BUILD"
        echo "VERSION: ${{ env.VERSION }}"
        echo "All environment variables:"
        env
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: 'cicd_test' 
        filters: |
          menu:
            - 'src/menu/**'
          waiter:
            - 'src/waiter/**'
          chef:
            - 'src/chef/**'

  build-menu:
    needs: check-changes
    if: needs.check-changes.outputs.menu == 'true' || needs.check-changes.outputs.force_build == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_URL }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    - name: Build and push Menu service
      uses: docker/build-push-action@v5
      with:
        context: ./src/menu
        push: true
        tags: |
          ${{ secrets.AZURE_ACR_URL }}/menu:latest
          ${{ secrets.AZURE_ACR_URL }}/menu:${{ env.VERSION }}

  build-waiter:
    needs: check-changes
    if: needs.check-changes.outputs.waiter == 'true' || needs.check-changes.outputs.force_build == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_URL }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    - name: Build and push Waiter service
      uses: docker/build-push-action@v5
      with:
        context: ./src/waiter
        push: true
        tags: |
          ${{ secrets.AZURE_ACR_URL }}/waiter:latest
          ${{ secrets.AZURE_ACR_URL }}/waiter:${{ env.VERSION }}

  build-chef:
    needs: check-changes
    if: needs.check-changes.outputs.chef == 'true' || needs.check-changes.outputs.force_build == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_URL }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    - name: Build and push Chef service
      uses: docker/build-push-action@v5
      with:
        context: ./src/chef
        push: true
        tags: |
          ${{ secrets.AZURE_ACR_URL }}/chef:latest
          ${{ secrets.AZURE_ACR_URL }}/chef:${{ env.VERSION }}

  deploy:
    needs: [check-changes, build-menu, build-waiter, build-chef]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    - name: Configure Kubernetes to connect to Minikube
      run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONF }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config set clusters.minikube.server https://${{ secrets.LOCALKUBEIP }}:8443
          kubectl config use-context minikube
          kubectl cluster-info || exit 1
    - name: Create ACR Secret
      run: |
        if kubectl get secret acr-secret; then
          echo "Secret acr-secret already exists, skipping creation."
        else
          kubectl create secret docker-registry acr-secret \
            --docker-server=${{ secrets.AZURE_ACR_URL }} \
            --docker-username=${{ secrets.AZURE_ACR_USERNAME }} \
            --docker-password=${{ secrets.AZURE_ACR_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -
        fi
    - name: Deploy to Kubernetes
      run: |
        if helm list | grep -q "restaurant"; then
          helm upgrade restaurant ./src/restaurant \
            --set menu.image.tag=${{ needs.check-changes.outputs.menu == 'true' && env.VERSION || 'latest' }} \
            --set waiter.image.tag=${{ needs.check-changes.outputs.waiter == 'true' && env.VERSION || 'latest' }} \
            --set chef.image.tag=${{ needs.check-changes.outputs.chef == 'true' && env.VERSION || 'latest' }} 

          ${{ needs.check-changes.outputs.menu == 'true' }} && kubectl rollout restart deployment menu || true
          ${{ needs.check-changes.outputs.waiter == 'true' }} && kubectl rollout restart deployment waiter || true
          ${{ needs.check-changes.outputs.chef == 'true' }} && kubectl rollout restart deployment chef || true
        else
          # For initial install, always use latest
          helm install restaurant ./src/restaurant \
            --set menu.image.tag=latest \
            --set waiter.image.tag=latest \
            --set chef.image.tag=latest 
        fi